### ISSUE TITLE
Error if plugin disables itself

### ISSUE THREAD

**Issue by 1ByteBit** [WorldDynamics-MC/WorldDynamics-Engine#13]
If vault/towny isn't installed, the plugin disables itself. This however causes an error as it attempts to save data despite it being null. `NationManager.saveNations()` being the most obvious. This is the same error shown in #6, except I've confirmed it appears if the plugin disables itself at all during startup.

**Comment by 1ByteBit** [comment]
I've looked into it a bit more and from what it seems the issue is only fixed by having an if statement for any null values of the saves in ondisable, however now the following error appears which I have no idea what could be causing. Either an issue with paper, or something with the files?
```[21:47:14 ERROR]: Error occurred while enabling WorldDynamicsEngine v0.1.7 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:845) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:337) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.thatguycy.worlddynamicsengine.WorldDynamicsEngine.onEnable(WorldDynamicsEngine.java:70) ~[WorldDynamicsEngine-0.1.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-389]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-389]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by thatguycy** [comment]
Hi, I'm unable to replicate your error?

Please give a step-by-step, including server version/build, etc, thanks!

**Comment by 1ByteBit** [comment]
The error is definitely specific. It's more then likely something on my end. I'll check it in a couple different environments but it's probably safe to assume that error isn't of importance if you don't have an issue with it

**Comment by 1ByteBit** [comment]
Oh, but for the record I'm using Java 21 and the latest version of paper. No other errors similar to this in the console. I've looked around online and this seems to be a bit of a big error, usually around an older java version? Worst case scenario, it only happens if the plugin shutdowns due to lacking its dependencies it seems.
